URL_ABENGOUROU = "http://www.pagesjaunes.ci/pharmacies-de-garde-abengourou/"
URL_ABOISSO = "http://www.pagesjaunes.ci/pharmacies-de-garde-aboisso/"
URL_AGBOVILLE = "http://www.pagesjaunes.ci/pharmacies-de-garde-agboville/"
URL_AGNIBILEKRO = "http://www.pagesjaunes.ci/pharmacies-de-garde-agnibilekrou/"
URL_ALEPE = "http://www.pagesjaunes.ci/pharmacies-de-garde-alepe/"
URL_ANYAMA = "http://www.pagesjaunes.ci/pharmacies-de-garde-anyama/"
URL_BINGERVILLE = "http://www.pagesjaunes.ci/pharmacies-de-garde-bingerville/"

URL_ABOBO = "http://www.pagesjaunes.ci/pharmacies-de-garde-abobo/"
URL_ADJAME = "http://www.pagesjaunes.ci/pharmacies-de-garde-adjame"
URL_COCODY = "http://www.pagesjaunes.ci/pharmacies-de-garde-cocody/"
URL_KOUMASSI = "http://www.pagesjaunes.ci/pharmacies-de-garde-koumassi/"
URL_MARCORY = "http://www.pagesjaunes.ci/pharmacies-de-garde-marcory/"
URL_PLATEAU = "http://www.pagesjaunes.ci/pharmacies-de-garde-plateau/"
URL_TREICHVILLE = "http://www.pagesjaunes.ci/pharmacies-de-garde-treichville/"
URL_YOPOUGON = "http://www.pagesjaunes.ci/pharmacies-de-garde-yopougon/"